spring:
  ai:
    alibaba:
      toolcalling:
        baidu:
          translate:
            enabled: true
            app-id: 20250719002410841
            secret-key: qOrul24H1s3SJNv4HGiT
          map:
            enabled: true
            apiKey: 090dBBVCmW24VWOhqksHuyclbX5snMzy

        time:
          enabled: true

        weather:
          enabled: true
          api-key: ${WEATHER_API_KEY}

    dashscope:
      api-key: sk-f48466cf0ae84a3ead60ffc6a823e1fb
